In [ ]:
import numpy as np


In [ ]:
np.logspace(1,3,5)


array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])

# metrix

In [ ]:
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(5,2)           # it can give uneven row and column     5 row    2 column


array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.identity(5)           # it requires  same row and column 5 * 5


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.diag([2,3,4,5])       # it will generate diagonal list with rest 0's


array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [12]:
np.random.rand(1)         # random number between 0 to 1


array([0.0972352])

In [ ]:
np.random.rand(10)


array([0.38310853, 0.65292506, 0.43938328, 0.56625374, 0.0554247 ,
       0.5670625 , 0.52359402, 0.25512793, 0.47236993, 0.51999646])

In [ ]:
np.random.rand(3,4)               # 3 * 4 metrix with 3 rows and 4 columns and values between 0 to 1


array([[0.22221706, 0.61268687, 0.76575005, 0.10557452],
       [0.78247024, 0.61572071, 0.12862734, 0.01216803],
       [0.95983141, 0.37459506, 0.43801656, 0.93336679]])

In [ ]:
np.random.randint(1,10,5)


array([7, 3, 7, 3, 3])

In [ ]:
# dice from snack and ladder

dice = np.random.randint(1,6,1)
dice


array([4])

In [ ]:
np.random.randn(10)             # gives normally distributed values


array([ 0.04346594,  0.32816584, -0.28201391, -0.82950862, -0.3655547 ,
        1.5060076 , -1.02193622,  0.79639343,  1.03541908, -1.02218155])

In [ ]:
np.random.choice([1,10,2],20)             # starting 1 to 10 and step 2 with 20 values       mostly used to generate random value


array([ 1, 10,  2,  2, 10,  2,  2,  1,  1,  1,  1,  2,  2, 10, 10,  1,  1,
        2, 10, 10])

In [ ]:
np.random.seed(10)
np.random.rand()


0.771320643266746

# Deep and shallow copy

In [ ]:
a = [1,2,3,4,5,6]
b = np.copy(a)         # deep copy


In [ ]:
a


[1, 2, 3, 4, 5, 6]

In [ ]:
b


array([1, 2, 3, 4, 5, 6])

In [ ]:
a[0] = 100
a


[100, 2, 3, 4, 5, 6]

In [ ]:
b[0] = 1000


In [ ]:
b


array([1000,    2,    3,    4,    5,    6])

In [ ]:
a


[100, 2, 3, 4, 5, 6]

In [86]:
a = np.array([1,2,3,4,5,6])
a


array([1, 2, 3, 4, 5, 6])

In [ ]:
b = a.view()          # Shallow copy


In [ ]:
b


array([1, 2, 3, 4, 5, 6])

In [ ]:
a[0]= 10000


In [ ]:
print(a, b)


[10000     2     3     4     5     6] [10000     2     3     4     5     6]


In [ ]:
b[0] = 12345
print(a, b)


[12345     2     3     4     5     6] [12345     2     3     4     5     6]


In [ ]:
np.full([5,2],10)          # 5 - row, 2-column , 10 - value


array([[10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10]])

In [ ]:
a = np.arange(1,11)


In [ ]:
np.where(a<=5,True,False)


array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [ ]:
a = [[[[1,2], [3,4]],
      [4,1],[5,6]],
      [[[6,1], [7,8]],
      [8,6],[7,1]]]


In [ ]:
a[1]


[[[6, 1], [7, 8]], [8, 6], [7, 1]]

In [ ]:
a[1][0]


[[6, 1], [7, 8]]

In [ ]:
a[1][0][0]


[6, 1]

In [ ]:
a[1][0][0][0]


6

In [ ]:
a = np.random.rand(2,2,2,2)
a


array([[[[0.38804945, 0.86649164],
         [0.95685333, 0.48655367]],

        [[0.10593306, 0.34003729],
         [0.83557079, 0.46544163]]],


       [[[0.09285611, 0.85469414],
         [0.33725819, 0.60614675]],

        [[0.1126646 , 0.54392045],
         [0.72079858, 0.86581537]]]])

In [ ]:
a[0][0][:2][:1][1:]


array([], shape=(0, 2), dtype=float64)

In [ ]:
for i in a:
    print(i)
    print('*'*50)
    for j in i:
        print(j)
        print('o'*50)
        for k in j:
            print(k)
            print('😀'*50)
            for l in k:
                print(l)
                print('.'*50)


[[[0.38804945 0.86649164]
  [0.95685333 0.48655367]]

 [[0.10593306 0.34003729]
  [0.83557079 0.46544163]]]
**************************************************
[[0.38804945 0.86649164]
 [0.95685333 0.48655367]]
oooooooooooooooooooooooooooooooooooooooooooooooooo
[0.38804945 0.86649164]
😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀
0.3880494533391232
..................................................
0.8664916406550097
..................................................
[0.95685333 0.48655367]
😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀
0.9568533263731646
..................................................
0.4865536688050681
..................................................
[[0.10593306 0.34003729]
 [0.83557079 0.46544163]]
oooooooooooooooooooooooooooooooooooooooooooooooooo
[0.10593306 0.34003729]
😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀
0.10593305856565993
..................................................
0.34003728865290284
.........................................

In [ ]:
# find out the index of element, who's value is equal to given value.


ma = [[10,20,30],
      [20,50,40],
      [70,80,20]
      ]
ma

value = 70


In [192]:
for i in range(len(ma)):
    #print(i,ma[i])
    for j in range(len(ma[i])):
        #print(j)
        print(i,j, '=', ma[i][j])    # to find out the postion and value of the matrix
    
        

0 0 = 10
0 1 = 20
0 2 = 30
1 0 = 20
1 1 = 50
1 2 = 40
2 0 = 70
2 1 = 80
2 2 = 20


In [ ]:
# to find the position of value = 20


for i in range(len(ma)):
    for j in range(len(ma[i])):
        if ma[i][j] == value:
            print(i,j)


2 0


### Question: Find out the 2 values who's some equals to given value



In [ ]:
ma = [10,20,30,
      20,50, 40,
      70, 80,20]

value = 100


In [ ]:
l = []

for i in ma:
    for j in ma:
        if i+j == value:
            if sorted([i,j]) not in l:
                l.append(sorted([i,j]))
print(l)


[[20, 80], [30, 70], [50, 50]]
